#
# This file contains configuration flags to customize your site
#
# Name of your site (The Mind of a Jack of All Trades)
title: The Bloggiest
# Short bio or description (How does somoene who wants to learn every useless talent see the world)
description: A Blog that is about the most memable student at CNU, this is an academic blog, enjoy my offbeat takes.

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
